# Generated by Django 4.2.7 on 2024-03-14 18:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tablamadre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MecanicoEncargado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=512)),
                ('nombre', models.CharField(max_length=512)),
                ('apellido', models.CharField(max_length=512)),
                ('precio_hora', models.PositiveIntegerField()),
                ('archivos_adjuntos', models.FileField(default='default_value', upload_to='Archivos_adjuntos')),
            ],
            options={
                'verbose_name_plural': 'Mecanicos Encargados',
                'permissions': [('puede_ver_mecanicos_encargados', 'Puede ver los mecanicos encargados'), ('puede_crear_mecanicos_encargados', 'Puede crear los mecanicos encargados')],
            },
        ),
        migrations.CreateModel(
            name='OrdenDeReparacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Ordenes de Reparacion',
                'permissions': [('puede_ver_ordenes_reparacion', 'Puede ver las ordenes de reparacion'), ('puede_crear_ordenes_reparacion', 'Puede crear las ordenes de reparacion')],
            },
        ),
        migrations.CreateModel(
            name='ReparacionTemporal',
            fields=[
                ('interno', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(default='Generica', max_length=256)),
                ('supervisor', models.CharField(default='Generica', max_length=256)),
                ('mecanico_encargado', models.CharField(max_length=512)),
                ('falla_general', models.CharField(default='Generica', max_length=512)),
                ('horas_km_entrada', models.CharField(default='Generica', max_length=512)),
                ('fecha_entrada', models.CharField(default='Generica', max_length=512)),
                ('fecha_reparacion', models.CharField(default='Generica', max_length=512)),
                ('estado_reparacion', models.CharField(default='Generica', max_length=512)),
                ('estado_equipo', models.CharField(default='Generica', max_length=512)),
                ('apto_traslado', models.CharField(default='X', max_length=512)),
                ('descripcion', models.CharField(default='Generica', max_length=512)),
                ('orden_reparacion', models.CharField(default='Generica', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=512)),
                ('ubicacion', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name_plural': 'Talleres',
            },
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('falla_general', models.CharField(max_length=256)),
                ('horas_km_entrada', models.PositiveIntegerField()),
                ('fecha_entrada', models.DateTimeField()),
                ('fecha_reparacion', models.DateTimeField()),
                ('estado_reparacion', models.CharField(max_length=100)),
                ('estado_equipo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=256)),
                ('apto_traslado', models.BooleanField()),
                ('interno', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos')),
                ('mecanico_encargado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reparaciones.mecanicoencargado')),
                ('orden_reparacion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reparaciones.ordendereparacion')),
                ('supervisor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reparaciones.supervisor')),
                ('taller', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reparaciones.taller')),
            ],
            options={
                'verbose_name_plural': 'Reparaciones',
                'permissions': [('puede_ver_reparaciones', 'Puede ver las reparaciones'), ('puede_crear_reparaciones', 'Puede crear las reparaciones')],
            },
        ),
        migrations.CreateModel(
            name='ParteDiarioMecanicos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('actividad', models.CharField(max_length=512)),
                ('mecanico', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reparaciones.mecanicoencargado')),
            ],
            options={
                'verbose_name_plural': 'Partes Diarios Mecanicos',
                'permissions': [('puede_ver_partes_diarios_mecanicos', 'Puede ver los partes diarios mecanicos'), ('puede_crear_partes_diarios_mecanicos', 'Puede crear los partes diarios mecanicos')],
            },
        ),
        migrations.CreateModel(
            name='OrdenDeReparacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(default='None', max_length=100)),
                ('nombre', models.CharField(default='None', max_length=200)),
                ('cantidad', models.PositiveIntegerField()),
                ('orden_de_reparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.ordendereparacion')),
            ],
            options={
                'verbose_name_plural': 'Items de Orden de Reparacion',
            },
        ),
        migrations.AddField(
            model_name='mecanicoencargado',
            name='taller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reparaciones.taller'),
        ),
        migrations.AddField(
            model_name='mecanicoencargado',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
