# Generated by Django 4.2.7 on 2024-01-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReparacionTemporal',
            fields=[
                ('interno', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(default='Generica', max_length=256)),
                ('taller', models.CharField(default='Generico', max_length=512)),
                ('mecanico_encargado', models.CharField(max_length=512)),
                ('falla_general', models.CharField(default='Generica', max_length=512)),
                ('fechareparacionestimada', models.CharField(default='Generica', max_length=512)),
                ('fechaentrada', models.CharField(default='Generica', max_length=512)),
                ('fechasalida', models.IntegerField(default=1)),
                ('estadoreparacion', models.CharField(default='Generica', max_length=512)),
                ('estadoequipo', models.CharField(default='Generica', max_length=512)),
                ('descripcion', models.CharField(default='Generica', max_length=512)),
            ],
        ),
    ]
