# Generated by Django 4.2.7 on 2024-03-08 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tablamadre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDeReparacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': [('puede_ver_ordenes_reparacion', 'Puede ver las ordenes de reparacion'), ('puede_crear_ordenes_reparacion', 'Puede crear las ordenes de reparacion')],
            },
        ),
        migrations.CreateModel(
            name='ReparacionTemporal',
            fields=[
                ('interno', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(default='Generica', max_length=256)),
                ('supervisor', models.CharField(default='Generica', max_length=256)),
                ('mecanico_encargado', models.CharField(max_length=512)),
                ('falla_general', models.CharField(default='Generica', max_length=512)),
                ('horas_km_entrada', models.CharField(default='Generica', max_length=512)),
                ('fecha_entrada', models.CharField(default='Generica', max_length=512)),
                ('fecha_reparacion', models.CharField(default='Generica', max_length=512)),
                ('estado_reparacion', models.CharField(default='Generica', max_length=512)),
                ('estado_equipo', models.CharField(default='Generica', max_length=512)),
                ('apto_traslado', models.CharField(default='X', max_length=512)),
                ('descripcion', models.CharField(default='Generica', max_length=512)),
                ('orden_reparacion', models.CharField(default='Generica', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('falla_general', models.CharField(max_length=256)),
                ('horas_km_entrada', models.PositiveIntegerField()),
                ('fecha_entrada', models.DateTimeField()),
                ('fecha_reparacion', models.DateTimeField()),
                ('estado_reparacion', models.CharField(max_length=100)),
                ('estado_equipo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=256)),
                ('apto_traslado', models.BooleanField()),
                ('interno', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos')),
                ('mecanico_encargado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.mecanicosencargados')),
                ('orden_reparacion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reparaciones.ordendereparacion')),
                ('supervisor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reparaciones.supervisor')),
                ('taller', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.talleres')),
            ],
            options={
                'permissions': [('puede_ver_reparaciones', 'Puede ver las reparaciones'), ('puede_crear_reparaciones', 'Puede crear las reparaciones')],
            },
        ),
        migrations.CreateModel(
            name='OrdenDeReparacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(default='None', max_length=100)),
                ('nombre', models.CharField(default='None', max_length=200)),
                ('cantidad', models.PositiveIntegerField()),
                ('orden_de_reparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.ordendereparacion')),
            ],
        ),
    ]
