# Generated by Django 4.2.7 on 2024-03-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partediariomecanicos',
            name='horas',
            field=models.FloatField(default=0.0),
        ),
    ]
