# Generated by Django 4.2.7 on 2024-01-25 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reparaciontemporal',
            name='taller',
        ),
    ]
