# Generated by Django 4.2.7 on 2024-03-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendereparacion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
