# Generated by Django 4.2.7 on 2024-01-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0002_remove_reparaciontemporal_taller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparaciontemporal',
            name='fechasalida',
            field=models.CharField(default='Generica', max_length=512),
        ),
    ]
