# Generated by Django 4.2.7 on 2024-03-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0002_alter_ordendereparacion_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendereparacion',
            name='items',
        ),
        migrations.RemoveField(
            model_name='ordendereparacionitem',
            name='item',
        ),
        migrations.AddField(
            model_name='ordendereparacionitem',
            name='item_id',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='ordendereparacionitem',
            name='nombre',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
