# Generated by Django 4.2.7 on 2024-03-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0002_partediariomecanicos_horas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParteTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('mecanico', models.CharField(max_length=512)),
                ('actividad', models.CharField(max_length=1024)),
                ('horas', models.CharField(max_length=512)),
            ],
        ),
    ]
