# Generated by Django 4.2.7 on 2024-03-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0003_partetemporal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partetemporal',
            name='fecha',
            field=models.DateField(),
        ),
    ]
