# Generated by Django 4.2.7 on 2024-02-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0003_alter_reparaciontemporal_fechasalida'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparaciontemporal',
            name='apto_traslado',
            field=models.CharField(default='X', max_length=512),
        ),
    ]
