# Generated by Django 4.2.7 on 2024-03-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0004_alter_partetemporal_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendereparacionitem',
            name='almacen',
            field=models.CharField(default='Central', max_length=100),
        ),
    ]
