# Generated by Django 4.2.7 on 2024-03-24 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0008_certificadosequiposalquilados_interno'),
        ('reparaciones', '0005_ordendereparacionitem_almacen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendereparacion',
            name='up',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.unidadesdeproduccion'),
        ),
    ]
