# Generated by Django 4.2.7 on 2023-11-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadesProduccionTabla',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('unidadproduccion', models.CharField(max_length=512)),
                ('ubicacion', models.CharField(max_length=512)),
            ],
        ),
    ]
