# Generated by Django 4.2.7 on 2024-03-11 18:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tablamadre', '0003_alter_consumo_hskmactuales_and_more'),
        ('reparaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTwo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_requeridoobra', models.DateTimeField()),
                ('solicitante', models.CharField(max_length=500)),
                ('descripcion', models.CharField(max_length=500)),
                ('materiales', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reparaciones.ordendereparacion')),
                ('nivel_urgencia', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.urgencia')),
                ('up_solicita', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.unidadesdeproduccion')),
            ],
        ),
        migrations.CreateModel(
            name='FormOne',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_requeridoobra', models.DateTimeField()),
                ('solicitante', models.CharField(max_length=500)),
                ('tipo_equipo', models.CharField(max_length=500)),
                ('descripcion_equipo', models.CharField(max_length=500)),
                ('motivo_requerimiento', models.CharField(max_length=500)),
                ('tope_requerimiento', models.DateTimeField()),
                ('nivel_urgencia', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.urgencia')),
                ('repuesto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reparaciones.ordendereparacion')),
                ('up_solicita', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.unidadesdeproduccion')),
            ],
        ),
        migrations.CreateModel(
            name='FormCombination',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_requeridoobra', models.DateTimeField()),
                ('solicitante', models.CharField(max_length=500)),
                ('materiales', models.CharField(max_length=500)),
                ('descripcion', models.CharField(max_length=500)),
                ('nivel_urgencia', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.urgencia')),
                ('repuesto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reparaciones.ordendereparacion')),
                ('up_solicita', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.unidadesdeproduccion')),
            ],
        ),
    ]
