# Generated by Django 4.2.7 on 2024-04-17 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tablamadre', '0008_certificadosequiposalquilados_interno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitarLogistica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_equipo', models.CharField(max_length=500)),
                ('descripcion_equipo', models.CharField(max_length=500)),
                ('motivo_requerimiento', models.CharField(max_length=700)),
                ('fecha_requerido', models.DateTimeField()),
                ('tope_requerimiento', models.DateTimeField()),
                ('observacion', models.CharField(max_length=2000)),
                ('nivel_urgencia', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.urgencia')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormEquipos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('carreton_propio', models.BooleanField(default=True)),
                ('proovedor', models.CharField(max_length=500)),
                ('tara', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_requeridoobra', models.DateTimeField()),
                ('fecha_envio', models.DateTimeField()),
                ('solicitante', models.CharField(max_length=500)),
                ('hsKm', models.IntegerField()),
                ('tope_requerimiento', models.DateTimeField()),
                ('valor_viaje', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chofer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.choferes')),
                ('equipo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos')),
                ('solicitud', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logisticas.solicitarlogistica')),
                ('up_solicita', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.unidadesdeproduccion')),
            ],
        ),
        migrations.CreateModel(
            name='FormCombination',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_traslado', models.CharField(max_length=1000)),
                ('carreton_propio', models.BooleanField(default=True)),
                ('proovedor', models.CharField(max_length=500)),
                ('tara', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_requeridoobra', models.DateTimeField()),
                ('fecha_envio', models.DateTimeField()),
                ('descripcion', models.CharField(max_length=500)),
                ('valor_viaje', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chofer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.choferes')),
                ('equipo_traslada', models.ForeignKey(default='alquilado', on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos')),
                ('up_solicita', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.unidadesdeproduccion')),
            ],
        ),
    ]
