# Generated by Django 4.2.7 on 2023-12-04 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('interno', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=256)),
                ('modelo', models.CharField(max_length=512)),
                ('chasis', models.CharField(max_length=512)),
                ('motor', models.CharField(max_length=512)),
                ('anio', models.IntegerField()),
                ('aseguradora', models.CharField(max_length=512)),
                ('seguro', models.CharField(max_length=512)),
                ('seguro_pdf', models.CharField(max_length=512)),
                ('itv', models.CharField(max_length=512)),
                ('itv_pdf', models.CharField(max_length=512)),
                ('titulo_pdf', models.CharField(max_length=512)),
                ('tarjeta', models.CharField(max_length=256)),
                ('tarjeta_pdf', models.CharField(max_length=512)),
                ('propietario', models.CharField(max_length=512)),
                ('chofer', models.CharField(max_length=512)),
                ('alquilado', models.BooleanField(default=False)),
                ('valorpesos', models.IntegerField()),
                ('valordolares', models.IntegerField()),
                ('orden', models.CharField(max_length=512)),
                ('actividadvehiculo', models.CharField(max_length=512)),
                ('dominio', models.CharField(default='default_value', max_length=255)),
                ('tipovehiculo', models.CharField(default='valor_predeterminado', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Logistica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('carreton', models.CharField(max_length=512)),
                ('choferlogistica', models.CharField(max_length=512)),
                ('numeroremito', models.CharField(max_length=512)),
                ('proveedor', models.CharField(max_length=512)),
                ('origen', models.CharField(max_length=512)),
                ('destino', models.CharField(max_length=512)),
                ('kmentredestinos', models.IntegerField()),
                ('transporte', models.CharField(max_length=512)),
                ('consumokmxlitros', models.IntegerField()),
                ('valorviaje', models.IntegerField()),
                ('interno', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos')),
            ],
        ),
        migrations.CreateModel(
            name='PartesDiarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proveedores', models.CharField(max_length=512)),
                ('razonsocial', models.CharField(max_length=512)),
                ('cantidadequipos', models.IntegerField()),
                ('kilometrajeinicial', models.IntegerField()),
                ('kilometrajefinal', models.IntegerField()),
                ('turnoreparacion', models.CharField(max_length=512)),
                ('horometro', models.IntegerField()),
                ('hsxkmcarga', models.IntegerField()),
                ('tipocombustible', models.CharField(max_length=512)),
                ('tipogasoil', models.CharField(max_length=512)),
                ('tiponafta', models.CharField(max_length=512)),
                ('litrosgasoil', models.IntegerField()),
                ('litrosnafta', models.IntegerField()),
                ('tipoaceite', models.CharField(max_length=512)),
                ('litrosaceite', models.IntegerField()),
                ('maquinista', models.CharField(max_length=512)),
                ('kmsxhs', models.IntegerField()),
                ('tipodefalla', models.CharField(default='No hay falla', max_length=512)),
                ('reparado', models.BooleanField(default=False)),
                ('interno', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos')),
            ],
        ),
        migrations.CreateModel(
            name='Reparaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(default='Taller', max_length=512)),
                ('falla', models.CharField(max_length=512)),
                ('porcentajeavance', models.IntegerField()),
                ('fechareparacionestimada', models.DateTimeField()),
                ('fechaentrada', models.DateTimeField()),
                ('fechasalida', models.DateTimeField()),
                ('estadoreparacion', models.CharField(max_length=512)),
                ('estadoequipo', models.CharField(max_length=512)),
                ('interno', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaservicio', models.DateTimeField()),
                ('fechaparte', models.DateTimeField()),
                ('ultimoservice', models.IntegerField()),
                ('planrealizado_hs', models.IntegerField()),
                ('planrealizado', models.CharField(max_length=512)),
                ('proximoservice', models.IntegerField()),
                ('hsxkmactuales', models.IntegerField()),
                ('hsxkmrestantes', models.IntegerField()),
                ('necesidadservice', models.CharField(max_length=512)),
                ('interno', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadesdeProduccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unidadproduccion', models.CharField(max_length=15)),
                ('ubicacion', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='TablaMadre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('dolardia', models.IntegerField()),
                ('observaciones', models.CharField(max_length=512)),
                ('internos', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos')),
                ('logistica', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.logistica')),
                ('partesdiarions', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.partesdiarios')),
                ('reparaciones', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.reparaciones')),
                ('services', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.services')),
                ('unidadesdeproduccion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.unidadesdeproduccion')),
            ],
        ),
        migrations.CreateModel(
            name='Novedades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reparado', models.BooleanField(default=False)),
                ('interno', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos')),
            ],
        ),
        migrations.AddField(
            model_name='internos',
            name='up',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.unidadesdeproduccion'),
        ),
    ]
