# Generated by Django 4.2.7 on 2024-03-14 18:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadosEquiposAlquilados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contratista', models.CharField(max_length=512)),
                ('obra', models.CharField(max_length=512)),
                ('periodo_certificado', models.CharField(max_length=512)),
                ('equipo_alquilado', models.CharField(max_length=512)),
                ('unidad', models.CharField(default='Mes', max_length=3)),
                ('certificado_en_mes', models.FloatField()),
                ('acumulado', models.FloatField()),
                ('precio_unitario', models.FloatField()),
                ('importe', models.FloatField()),
                ('total_neto_deducciones', models.FloatField()),
                ('total_con_iva', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('mes', models.CharField(default='enero', max_length=15)),
                ('anio', models.IntegerField(default=2024)),
            ],
        ),
        migrations.CreateModel(
            name='Choferes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=512)),
                ('apellido', models.CharField(max_length=512)),
                ('fecha_ingreso', models.DateTimeField()),
                ('dni', models.BigIntegerField()),
                ('licencia', models.FileField(default='default_value', upload_to='Licencias')),
                ('dni_pdf', models.FileField(default='default_value', upload_to='DNI')),
            ],
            options={
                'permissions': [('puede_ver_choferes', 'Puede ver los choferes'), ('puede_crear_choferes', 'Puede crear los choferes')],
            },
        ),
        migrations.CreateModel(
            name='Internos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('interno', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=256)),
                ('modelo', models.CharField(max_length=512)),
                ('chasis', models.CharField(max_length=512)),
                ('motor', models.CharField(max_length=512)),
                ('anio', models.IntegerField()),
                ('aseguradora', models.CharField(max_length=512)),
                ('seguro', models.CharField(max_length=512)),
                ('seguro_pdf', models.FileField(default='default_value', upload_to='Seguros')),
                ('itv', models.FileField(default='default_value', upload_to='ITV')),
                ('titulo', models.FileField(default='default_value', upload_to='Titulos')),
                ('tarjeta', models.FileField(default='default_value', upload_to='Tarjetas')),
                ('propietario', models.CharField(max_length=512)),
                ('alquilado', models.BooleanField(default=False)),
                ('valorpesos', models.IntegerField()),
                ('valordolares', models.IntegerField()),
                ('orden', models.CharField(max_length=512)),
                ('actividadvehiculo', models.CharField(max_length=512)),
                ('dominio', models.CharField(default='default_value', max_length=255)),
            ],
            options={
                'permissions': [('puede_ver_internos', 'Puede ver los internos')],
            },
        ),
        migrations.CreateModel(
            name='Operadores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=512)),
                ('apellido', models.CharField(max_length=512)),
                ('fecha_ingreso', models.DateTimeField()),
                ('dni', models.BigIntegerField()),
                ('licencia', models.FileField(default='default_value', upload_to='Licencias')),
                ('dni_pdf', models.FileField(default='default_value', upload_to='DNI')),
            ],
            options={
                'permissions': [('puede_ver_operadores', 'Puede ver los operadores'), ('puede_crear_operadores', 'Puede crear los operadores')],
            },
        ),
        migrations.CreateModel(
            name='Tanque',
            fields=[
                ('nombre', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('capacidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_combustible', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'permissions': [('puede_ver_tanques', 'Puede ver los tanques')],
            },
        ),
        migrations.CreateModel(
            name='TanqueAceite',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tipo_aceite', models.CharField(max_length=100)),
                ('capacidad_aceite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_aceite', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'permissions': [('puede_ver_aceites', 'Puede ver los aceites')],
            },
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=1)),
                ('descripcion', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadesdeProduccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unidadproduccion', models.CharField(max_length=15)),
                ('ubicacion', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Urgencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaservicio', models.DateTimeField()),
                ('fechaparte', models.DateTimeField()),
                ('ultimoservice', models.IntegerField()),
                ('planrealizado_hs', models.IntegerField()),
                ('planrealizado', models.CharField(max_length=512)),
                ('proximoservice', models.IntegerField()),
                ('hsxkmactuales', models.IntegerField()),
                ('hsxkmrestantes', models.IntegerField()),
                ('necesidadservice', models.CharField(max_length=512)),
                ('operativo', models.CharField(default='Operativo', max_length=512)),
                ('interno', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos')),
            ],
            options={
                'permissions': [('puede_ver_services', 'Puede ver los services')],
            },
        ),
        migrations.CreateModel(
            name='RepostajeAceite',
            fields=[
                ('remito', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('fecha_repostaje', models.DateTimeField()),
                ('cantidad_repostada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.CharField(max_length=500)),
                ('reservorio_aceite', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.tanqueaceite')),
            ],
            options={
                'permissions': [('puede_ver_cargarrepostaje', 'Puede ver los repostajes de aceites')],
            },
        ),
        migrations.CreateModel(
            name='Repostaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('remito', models.CharField(max_length=100, unique=True)),
                ('proveedor', models.CharField(default='PabloFederico', max_length=512)),
                ('tanque', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.tanque')),
            ],
            options={
                'permissions': [('puede_ver_repostaje', 'Puede ver los repostajes')],
            },
        ),
        migrations.CreateModel(
            name='Novedades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reparado', models.BooleanField(default=False)),
                ('tipo_falla', models.CharField(default='Generica', max_length=512)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('informacion', models.CharField(default='No hay informacion', max_length=512)),
                ('ingreso_hs_km', models.IntegerField(default=1)),
                ('chofer', models.CharField(default='No tiene chofer', max_length=512)),
                ('interno', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos')),
            ],
            options={
                'permissions': [('puede_ver_novedades', 'Puede ver la novedades')],
            },
        ),
        migrations.CreateModel(
            name='NeumaticosInternos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=512)),
                ('medida', models.CharField(max_length=512)),
                ('codigo', models.CharField(max_length=512)),
                ('interno', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos')),
            ],
        ),
        migrations.AddField(
            model_name='internos',
            name='tipovehiculo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.tipovehiculo'),
        ),
        migrations.AddField(
            model_name='internos',
            name='up',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.unidadesdeproduccion'),
        ),
        migrations.CreateModel(
            name='HistorialService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaservicio', models.DateTimeField()),
                ('fechaparte', models.DateTimeField()),
                ('ultimoservice', models.IntegerField()),
                ('planrealizado_hs', models.IntegerField()),
                ('planrealizado', models.CharField(max_length=512)),
                ('proximoservice', models.IntegerField()),
                ('hsxkmactuales', models.IntegerField()),
                ('hsxkmrestantes', models.IntegerField()),
                ('necesidadservice', models.CharField(max_length=512)),
                ('operativo', models.CharField(default='Operativo', max_length=512)),
                ('interno', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos')),
            ],
            options={
                'permissions': [('puede_ver_historial_service', 'Puede ver los services')],
            },
        ),
        migrations.CreateModel(
            name='FotoVehiculos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(default='default_value', upload_to='FotosVehiculos')),
                ('interno', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos')),
            ],
        ),
        migrations.CreateModel(
            name='FiltrosInternos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filtro', models.CharField(max_length=512)),
                ('marca', models.CharField(max_length=512)),
                ('codigo', models.CharField(max_length=512)),
                ('interno', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos')),
            ],
        ),
        migrations.CreateModel(
            name='DisponibilidadEquipos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso_de_obra', models.DateTimeField()),
                ('cantidad_de_dias_en_obra', models.IntegerField()),
                ('anio', models.IntegerField(default=2024)),
                ('mes', models.CharField(max_length=15)),
                ('dia', models.IntegerField()),
                ('actividad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.tipoactividad')),
                ('chofer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.choferes')),
                ('interno', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos')),
                ('up', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.unidadesdeproduccion')),
            ],
            options={
                'permissions': [('puede_ver_disponibilidad', 'Puede ver la disponibilidad')],
            },
        ),
        migrations.CreateModel(
            name='ConsumoAceite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_consumida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_consumo', models.DateTimeField()),
                ('hskmactuales', models.IntegerField()),
                ('observaciones', models.CharField(max_length=500)),
                ('chofer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.choferes')),
                ('interno', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos')),
                ('tanque_aceite', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.tanqueaceite')),
            ],
            options={
                'permissions': [('puede_ver_consumoaceite', 'Puede ver los consumos de aceite')],
            },
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consumo_litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_consumo', models.DateTimeField()),
                ('hskmactuales', models.BigIntegerField()),
                ('precinto_entrada', models.BigIntegerField()),
                ('precinto_salida', models.BigIntegerField()),
                ('observaciones', models.CharField(max_length=600)),
                ('chofer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.choferes')),
                ('interno', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos')),
                ('tanque', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.tanque')),
            ],
            options={
                'permissions': [('puede_ver_consumo', 'Puede ver los consumos')],
            },
        ),
        migrations.CreateModel(
            name='AlquilerEquipos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('solicitante', models.CharField(max_length=512)),
                ('revision', models.CharField(default='REVISIÓN 1', max_length=11)),
                ('r_comp', models.CharField(default='R-COMP-07', max_length=10)),
                ('fecha', models.DateTimeField()),
                ('monto_contratacion', models.IntegerField()),
                ('plazo_pago', models.CharField(max_length=512)),
                ('observaciones_contratacion', models.CharField(max_length=512)),
                ('fecha_inicio_tarea', models.DateTimeField()),
                ('periodo_contratacion', models.CharField(max_length=512)),
                ('periodo_finalizacion', models.CharField(max_length=512)),
                ('combustible_incluido', models.BooleanField(default=False)),
                ('operario_incluido', models.BooleanField(default=False)),
                ('art_operario', models.FileField(default='default_value', upload_to='ART')),
                ('observaciones_equipo', models.CharField(max_length=512)),
                ('titulo_tarjeta_verde', models.FileField(default='default_value', upload_to='Titulos')),
                ('kms', models.IntegerField()),
                ('estado', models.CharField(max_length=7)),
                ('inspeccion_equipo', models.BooleanField(default=False)),
                ('inspeccion_equipo_responsable', models.CharField(max_length=512)),
                ('forma_pago', models.CharField(max_length=512)),
                ('condicion_pago', models.CharField(max_length=512)),
                ('proveedor', models.CharField(max_length=512)),
                ('razon_social', models.CharField(max_length=512)),
                ('cbu', models.CharField(max_length=512)),
                ('telefono', models.CharField(max_length=512)),
                ('autorizado', models.BooleanField(default=False)),
                ('interno', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos')),
                ('up', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.unidadesdeproduccion')),
            ],
            options={
                'permissions': [('puede_ver_alquilados', 'Puede ver los alquilados')],
            },
        ),
    ]
