# Generated by Django 4.2.7 on 2023-11-13 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internos',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('interno', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=256)),
                ('modelo', models.CharField(max_length=512)),
                ('chasis', models.CharField(max_length=512)),
                ('motor', models.CharField(max_length=512)),
                ('anio', models.IntegerField()),
                ('aseguradora', models.CharField(max_length=512)),
                ('seguro', models.CharField(max_length=512)),
                ('seguro_pdf', models.CharField(max_length=512)),
                ('itv', models.CharField(max_length=512)),
                ('itv_pdf', models.CharField(max_length=512)),
                ('titulo_pdf', models.CharField(max_length=512)),
                ('tarjeta', models.CharField(max_length=256)),
                ('tarjeta_pdf', models.CharField(max_length=512)),
                ('propietario', models.CharField(max_length=512)),
                ('chofer', models.CharField(max_length=512)),
                ('alquilado', models.BooleanField(default=False)),
                ('valorpesos', models.IntegerField()),
                ('valordolares', models.IntegerField()),
                ('orden', models.CharField(max_length=512)),
                ('actividadvehiculo', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Logistica',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('carreton', models.CharField(max_length=512)),
                ('choferlogistica', models.CharField(max_length=512)),
                ('numeroremito', models.CharField(max_length=512)),
                ('proveedor', models.CharField(max_length=512)),
                ('origen', models.CharField(max_length=512)),
                ('destino', models.CharField(max_length=512)),
                ('kmentredestinos', models.IntegerField()),
                ('transporte', models.CharField(max_length=512)),
                ('consumokmxlitros', models.IntegerField()),
                ('valorviaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Novedades',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('tipofalla', models.CharField(max_length=512)),
                ('reparado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PartesDiarios',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('proveedores', models.CharField(max_length=512)),
                ('razonsocial', models.CharField(max_length=512)),
                ('cantidadequipos', models.IntegerField()),
                ('kilometrajeinicial', models.IntegerField()),
                ('kilometrajefinal', models.IntegerField()),
                ('turnoreparacion', models.CharField(max_length=512)),
                ('horometro', models.IntegerField()),
                ('hsxkmcarga', models.IntegerField()),
                ('tipocombustible', models.CharField(max_length=512)),
                ('tipogasoil', models.CharField(max_length=512)),
                ('tiponafta', models.CharField(max_length=512)),
                ('litrosgasoil', models.IntegerField()),
                ('litrosnafta', models.IntegerField()),
                ('tipoaceite', models.CharField(max_length=512)),
                ('litrosaceite', models.IntegerField()),
                ('maquinista', models.CharField(max_length=512)),
                ('kmsxhs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reparaciones',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('falla', models.CharField(max_length=512)),
                ('porcentajeavance', models.IntegerField()),
                ('fechareparacionestimada', models.DateTimeField()),
                ('fechaentrada', models.DateTimeField()),
                ('fechasalida', models.DateTimeField()),
                ('estadoreparacion', models.CharField(max_length=512)),
                ('estadoequipo', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('fechaservicio', models.DateTimeField()),
                ('fechaparte', models.DateTimeField()),
                ('ultimoservice', models.IntegerField()),
                ('planrealizado_hs', models.IntegerField()),
                ('planrealizado', models.CharField(max_length=512)),
                ('proximoservice', models.IntegerField()),
                ('hsxkmactuales', models.IntegerField()),
                ('hsxkmrestantes', models.IntegerField()),
                ('necesidadservice', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadesdeProduccion',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('unidadproduccion', models.CharField(max_length=15)),
                ('ubicacion', models.CharField(max_length=512)),
            ],
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='actividadvehiculo',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='alquilado',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='aseguradora',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='cantidadequipos',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='carreton',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='chasis',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='chofer',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='choferlogistica',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='consumokmxlitros',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='estadoequipo',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='estadoreparacion',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='falla',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='fechaentrada',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='fechaparte',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='fechareparacionestimada',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='fechasalida',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='fechaservicio',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='horometro',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='hsxkmactuales',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='hsxkmcarga',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='hsxkmrestantes',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='informacion',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='interno',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='itv',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='itv_pdf',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='kilometrajefinal',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='kilometrajeinicial',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='kmentredestinos',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='kmsxhs',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='litrosaceite',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='litrosgasoil',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='litrosnafta',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='maquinista',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='motor',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='necesidadservice',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='numeroremito',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='origen',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='planrealizado',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='planrealizado_hs',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='porcentajeavance',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='propietario',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='proveedores',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='proximoservice',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='razonsocial',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='reparado',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='seguro',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='seguro_pdf',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='tarjeta',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='tarjeta_pdf',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='tipoaceite',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='tipocombustible',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='tipofalla',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='tipogasoil',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='tiponafta',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='titulo_pdf',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='transporte',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='turnoreparacion',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='ultimoservice',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='valordolares',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='valorpesos',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='valorviaje',
        ),
        migrations.AlterField(
            model_name='tablamadre',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='tablamadre',
            name='internos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos'),
        ),
        migrations.AddField(
            model_name='tablamadre',
            name='logistica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.logistica'),
        ),
        migrations.AddField(
            model_name='tablamadre',
            name='novedades',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.novedades'),
        ),
        migrations.AddField(
            model_name='tablamadre',
            name='partesdiarions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.partesdiarios'),
        ),
        migrations.AddField(
            model_name='tablamadre',
            name='reparaciones',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.reparaciones'),
        ),
        migrations.AddField(
            model_name='tablamadre',
            name='services',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.services'),
        ),
        migrations.AlterField(
            model_name='tablamadre',
            name='unidadesdeproduccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.unidadesdeproduccion'),
        ),
    ]
