# Generated by Django 4.2.7 on 2024-03-14 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tablamadre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choferes',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='choferes',
            name='fecha_ingreso',
            field=models.DateField(),
        ),
    ]
