# Generated by Django 4.2.7 on 2023-12-04 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choferes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=512)),
                ('añoIngreso', models.DateTimeField()),
                ('dni', models.IntegerField()),
                ('licencia', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Consumos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('hsKm', models.IntegerField()),
                ('choferes', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.choferes')),
                ('interno', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos')),
            ],
        ),
    ]
