# Generated by Django 4.2.7 on 2024-01-11 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlquilerEquipos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('solicitante', models.CharField(max_length=512)),
                ('revision', models.CharField(default='REVISIÓN 1', max_length=11)),
                ('r_comp', models.CharField(default='R-COMP-07', max_length=10)),
                ('fecha', models.DateTimeField()),
                ('monto_contratacion', models.IntegerField()),
                ('observaciones_contratacion', models.CharField(max_length=512)),
                ('fecha_inicio_tarea', models.DateTimeField()),
                ('periodo_contratacion', models.CharField(max_length=512)),
                ('periodo_finalizacion', models.CharField(max_length=512)),
                ('combustible_incluido', models.BooleanField(default=False)),
                ('operario_incluido', models.BooleanField(default=False)),
                ('carnet_operario_vigente', models.BooleanField(default=False)),
                ('carnet_operario_fecha_vencimiento', models.DateTimeField()),
                ('art_operario', models.BooleanField(default=False)),
                ('observaciones_equipo', models.CharField(max_length=512)),
                ('tipo_vehiculo', models.CharField(max_length=512)),
                ('modelo', models.CharField(max_length=512)),
                ('marca', models.CharField(max_length=512)),
                ('dominio', models.CharField(max_length=512)),
                ('titulo_tarjeta_verde', models.CharField(max_length=512)),
                ('kms', models.IntegerField()),
                ('estado', models.CharField(max_length=7)),
                ('seguro_equipo', models.BooleanField(default=False)),
                ('inspeccion_equipo', models.BooleanField(default=False)),
                ('inspeccion_equipo_responsable', models.CharField(max_length=512)),
                ('forma_pago', models.CharField(max_length=512)),
                ('plazo_pago', models.CharField(max_length=512)),
                ('condicion_pago', models.CharField(max_length=512)),
                ('proveedor', models.CharField(max_length=512)),
                ('razon_social', models.CharField(max_length=512)),
                ('cbu', models.CharField(max_length=512)),
                ('telefono', models.CharField(max_length=512)),
                ('autorizado', models.BooleanField(default=False)),
                ('up', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.unidadesdeproduccion')),
            ],
        ),
    ]
