# Generated by Django 4.2.7 on 2024-03-08 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internos',
            name='chofer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.choferes'),
        ),
    ]
