# Generated by Django 4.2.7 on 2023-12-06 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0002_choferes_consumos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partesdiarios',
            old_name='cantidadequipos',
            new_name='cantida_de_quipos',
        ),
        migrations.RenameField(
            model_name='partesdiarios',
            old_name='kilometrajefinal',
            new_name='kilometraje_final',
        ),
        migrations.RenameField(
            model_name='partesdiarios',
            old_name='kilometrajeinicial',
            new_name='kilometraje_inicial',
        ),
        migrations.RenameField(
            model_name='partesdiarios',
            old_name='litrosaceite',
            new_name='litros_aceite',
        ),
        migrations.RenameField(
            model_name='partesdiarios',
            old_name='litrosgasoil',
            new_name='litros_gasoil',
        ),
        migrations.RenameField(
            model_name='partesdiarios',
            old_name='litrosnafta',
            new_name='litros_nafta',
        ),
        migrations.RenameField(
            model_name='partesdiarios',
            old_name='razonsocial',
            new_name='razon_social',
        ),
        migrations.RenameField(
            model_name='partesdiarios',
            old_name='tipoaceite',
            new_name='tipo_aceite',
        ),
        migrations.RenameField(
            model_name='partesdiarios',
            old_name='tipocombustible',
            new_name='tipo_combustible',
        ),
        migrations.RenameField(
            model_name='partesdiarios',
            old_name='tipodefalla',
            new_name='tipo_de_falla',
        ),
        migrations.RenameField(
            model_name='partesdiarios',
            old_name='tipogasoil',
            new_name='tipo_gasoil',
        ),
        migrations.RenameField(
            model_name='partesdiarios',
            old_name='tiponafta',
            new_name='tipo_nafta',
        ),
        migrations.RenameField(
            model_name='partesdiarios',
            old_name='turnoreparacion',
            new_name='turno_reparacion',
        ),
    ]
