# Generated by Django 4.2.7 on 2024-01-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0002_alquilerequipos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadosEquiposAlquilados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contratista', models.CharField(max_length=512)),
                ('obra', models.CharField(max_length=512)),
                ('periodo_certificado', models.CharField(max_length=512)),
                ('equipo_alquilado', models.CharField(max_length=512)),
                ('unidad', models.CharField(default='Mes', max_length=3)),
                ('certificado_en_mes', models.FloatField()),
                ('acumulado', models.FloatField()),
                ('precio_unitario', models.FloatField()),
                ('importe', models.FloatField()),
                ('total_neto_deducciones', models.FloatField()),
                ('total_con_iva', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
