# Generated by Django 4.2.7 on 2024-03-14 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tablamadre', '0002_choferes_usuario_alter_choferes_fecha_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='operadores',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
