# Generated by Django 4.2.7 on 2023-11-14 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0002_internos_logistica_novedades_partesdiarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internos',
            name='up',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.unidadesdeproduccion'),
        ),
        migrations.AddField(
            model_name='logistica',
            name='interno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos'),
        ),
        migrations.AddField(
            model_name='novedades',
            name='interno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos'),
        ),
        migrations.AddField(
            model_name='partesdiarios',
            name='interno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos'),
        ),
        migrations.AddField(
            model_name='reparaciones',
            name='interno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos'),
        ),
        migrations.AddField(
            model_name='services',
            name='interno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos'),
        ),
        migrations.AddField(
            model_name='unidadesdeproduccion',
            name='interno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos'),
        ),
    ]
