# Generated by Django 4.2.7 on 2024-03-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0002_alter_internos_chofer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='hskmactuales',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='precinto_entrada',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='precinto_salida',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='repostaje',
            name='remito',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='repostajeaceite',
            name='remito',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
