# Generated by Django 4.2.7 on 2023-11-14 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0003_internos_up_logistica_interno_novedades_interno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadesdeproduccion',
            name='interno',
        ),
    ]
