# Generated by Django 4.2.7 on 2024-03-11 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0003_alter_consumo_hskmactuales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logistica',
            name='interno',
        ),
        migrations.RemoveField(
            model_name='requerimientoequipo',
            name='up',
        ),
        migrations.RemoveField(
            model_name='requerimientotraslado',
            name='interno',
        ),
        migrations.DeleteModel(
            name='Cronogroma',
        ),
        migrations.DeleteModel(
            name='Logistica',
        ),
        migrations.DeleteModel(
            name='RequerimientoEquipo',
        ),
        migrations.DeleteModel(
            name='RequerimientoTraslado',
        ),
    ]
