# Generated by Django 4.2.7 on 2023-11-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0003_internos_up_logistica_interno_novedades_interno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novedades',
            old_name='interno',
            new_name='Internos',
        ),
        migrations.RemoveField(
            model_name='unidadesdeproduccion',
            name='interno',
        ),
        migrations.AddField(
            model_name='internos',
            name='dominio',
            field=models.CharField(default='default_value', max_length=255),
        ),
        migrations.AddField(
            model_name='internos',
            name='tipovehiculo',
            field=models.CharField(default='valor_predeterminado', max_length=255),
        ),
        migrations.AddField(
            model_name='partesdiarios',
            name='reparado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partesdiarios',
            name='tipodefalla',
            field=models.CharField(default='No hay falla', max_length=512),
        ),
        migrations.AddField(
            model_name='reparaciones',
            name='ubicacion',
            field=models.CharField(default='Taller', max_length=512),
        ),
        migrations.AlterField(
            model_name='internos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logistica',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='novedades',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='partesdiarios',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reparaciones',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='services',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unidadesdeproduccion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
