# Generated by Django 4.2.7 on 2023-12-11 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0003_rename_cantidadequipos_partesdiarios_cantida_de_quipos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=1)),
                ('descripcion', models.CharField(max_length=125)),
            ],
        ),
        migrations.RenameField(
            model_name='choferes',
            old_name='añoIngreso',
            new_name='anioIngreso',
        ),
        migrations.CreateModel(
            name='DisponibilidadEquipos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso_de_obra', models.DateTimeField()),
                ('cantidad_de_dias_en_obra', models.IntegerField()),
                ('mes', models.CharField(max_length=15)),
                ('dia', models.IntegerField()),
                ('actividad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.tipoactividad')),
                ('chofer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.choferes')),
                ('interno', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos')),
                ('up', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.unidadesdeproduccion')),
            ],
        ),
    ]
