# Generated by Django 4.2.7 on 2024-01-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0003_certificadosequiposalquilados'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadosequiposalquilados',
            name='anio',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='certificadosequiposalquilados',
            name='mes',
            field=models.CharField(default='enero', max_length=15),
        ),
    ]
