# Generated by Django 4.2.7 on 2024-03-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0003_operadores_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operadores',
            name='fecha_ingreso',
            field=models.DateField(),
        ),
    ]
