# Generated by Django 4.2.7 on 2023-11-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0004_remove_unidadesdeproduccion_interno'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparaciones',
            name='ubicacion',
            field=models.CharField(default='Taller', max_length=512),
        ),
    ]
