# Generated by Django 4.2.7 on 2023-11-23 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0004_rename_interno_novedades_internos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unidadesdeproduccion',
            old_name='id',
            new_name='interno_id',
        ),
    ]
