# Generated by Django 4.2.7 on 2024-01-19 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0004_certificadosequiposalquilados_anio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaservicio', models.DateTimeField()),
                ('fechaparte', models.DateTimeField()),
                ('ultimoservice', models.IntegerField()),
                ('planrealizado_hs', models.IntegerField()),
                ('planrealizado', models.CharField(max_length=512)),
                ('proximoservice', models.IntegerField()),
                ('hsxkmactuales', models.IntegerField()),
                ('hsxkmrestantes', models.IntegerField()),
                ('necesidadservice', models.CharField(max_length=512)),
                ('interno', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos')),
            ],
        ),
    ]
