# Generated by Django 4.2.7 on 2023-12-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0004_tipoactividad_rename_añoingreso_choferes_anioingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadequipos',
            name='anio',
            field=models.IntegerField(default=2024),
        ),
    ]
