# Generated by Django 4.2.7 on 2024-03-15 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0004_alter_operadores_fecha_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='choferes',
            name='interno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos'),
        ),
        migrations.AddField(
            model_name='operadores',
            name='interno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos'),
        ),
    ]
