# Generated by Django 4.2.7 on 2023-11-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0005_reparaciones_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
