# Generated by Django 4.2.7 on 2024-03-15 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0005_choferes_interno_operadores_interno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internos',
            options={'permissions': [('puede_ver_internos', 'Puede ver los internos'), ('puede_ver_info_internos', 'Puede ver los info internos')]},
        ),
        migrations.CreateModel(
            name='ArchivosAdjuntos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=512)),
                ('archivo', models.FileField(default='default_value', upload_to='ArchivosAdjuntos')),
                ('interno', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos')),
            ],
        ),
    ]
