# Generated by Django 4.2.7 on 2023-11-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0005_rename_id_unidadesdeproduccion_interno_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unidadesdeproduccion',
            old_name='interno_id',
            new_name='id',
        ),
    ]
