# Generated by Django 4.2.7 on 2023-11-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0006_alter_internos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparaciones',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
