# Generated by Django 4.2.7 on 2024-03-15 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0006_alter_internos_options_archivosadjuntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotovehiculos',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fotovehiculos',
            name='titulo',
            field=models.CharField(default='Foto', max_length=512),
        ),
    ]
