# Generated by Django 4.2.7 on 2024-01-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0006_services_operativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialservice',
            name='operativo',
            field=models.CharField(default='Operativo', max_length=512),
        ),
    ]
