# Generated by Django 4.2.7 on 2024-03-18 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0007_fotovehiculos_fecha_fotovehiculos_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadosequiposalquilados',
            name='interno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos'),
        ),
    ]
