# Generated by Django 4.2.7 on 2023-11-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0007_alter_reparaciones_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='partesdiarios',
            name='reparado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partesdiarios',
            name='tipodefalla',
            field=models.CharField(default='No hay falla', max_length=512),
        ),
    ]
