# Generated by Django 4.2.7 on 2024-01-22 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0007_historialservice_operativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedades',
            name='chofer',
            field=models.CharField(default='No tiene chofer', max_length=512),
        ),
        migrations.AddField(
            model_name='novedades',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='novedades',
            name='informacion',
            field=models.CharField(default='No hay informacion', max_length=512),
        ),
        migrations.AddField(
            model_name='novedades',
            name='ingreso_hs_km',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='novedades',
            name='tipo_falla',
            field=models.CharField(default='Generica', max_length=512),
        ),
    ]
