# Generated by Django 4.2.7 on 2023-11-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0008_partesdiarios_reparado_partesdiarios_tipodefalla'),
    ]

    operations = [
        migrations.AddField(
            model_name='internos',
            name='dominio',
            field=models.CharField(default='AAA0000', max_length=15),
        ),
    ]
