# Generated by Django 4.2.7 on 2024-02-03 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0008_novedades_chofer_novedades_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequerimientoTraslado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('origen', models.CharField(max_length=512)),
                ('destino', models.CharField(max_length=512)),
                ('fecha', models.DateTimeField()),
                ('aprobado', models.BooleanField(default=False)),
                ('interno', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos')),
            ],
        ),
        migrations.CreateModel(
            name='RequerimientoEquipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_equipo', models.CharField(max_length=512)),
                ('fecha_inicial', models.DateTimeField()),
                ('fecha_final', models.DateTimeField()),
                ('solicitante', models.CharField(max_length=512)),
                ('urgencia', models.CharField(max_length=512)),
                ('aprobado', models.BooleanField(default=False)),
                ('up', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.unidadesdeproduccion')),
            ],
        ),
        migrations.CreateModel(
            name='Cronogroma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('motivo_atraso', models.CharField(default='No hay motivo', max_length=512)),
                ('interno', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos')),
                ('up', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.unidadesdeproduccion')),
            ],
        ),
    ]
