# Generated by Django 4.2.7 on 2023-11-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0009_internos_dominio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internos',
            name='dominio',
            field=models.CharField(max_length=15),
        ),
    ]
