# Generated by Django 4.2.7 on 2024-02-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0009_requerimientotraslado_requerimientoequipo_cronogroma'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Urgencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=512)),
            ],
        ),
    ]
