# Generated by Django 4.2.7 on 2024-02-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0010_tipovehiculo_urgencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internos',
            name='itv_pdf',
            field=models.CharField(default='No', max_length=512),
        ),
        migrations.AlterField(
            model_name='internos',
            name='seguro_pdf',
            field=models.CharField(default='No', max_length=512),
        ),
        migrations.AlterField(
            model_name='internos',
            name='tarjeta_pdf',
            field=models.CharField(default='No', max_length=512),
        ),
        migrations.AlterField(
            model_name='internos',
            name='titulo_pdf',
            field=models.CharField(default='No', max_length=512),
        ),
    ]
