# Generated by Django 4.2.7 on 2023-11-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0010_alter_internos_dominio'),
    ]

    operations = [
        migrations.AddField(
            model_name='internos',
            name='tipovehiculo',
            field=models.CharField(default='Vehiculo Generico', max_length=512),
        ),
    ]
