# Generated by Django 4.2.7 on 2023-11-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0011_internos_tipovehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internos',
            name='tipovehiculo',
            field=models.CharField(max_length=512),
        ),
    ]
