# Generated by Django 4.2.7 on 2024-02-09 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0011_alter_internos_itv_pdf_alter_internos_seguro_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltrosInternos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filtro', models.CharField(max_length=512)),
                ('marca', models.CharField(max_length=512)),
                ('codigo', models.CharField(max_length=512)),
                ('interno', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos')),
            ],
        ),
    ]
