# Generated by Django 4.2.7 on 2024-02-09 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0012_filtrosinternos'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeumaticosInternos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=512)),
                ('medida', models.CharField(max_length=512)),
                ('codigo', models.CharField(max_length=512)),
                ('interno', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos')),
            ],
        ),
    ]
