# Generated by Django 4.2.7 on 2024-02-09 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0013_neumaticosinternos'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparaciones',
            name='apto_traslado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='logistica',
            name='consumokmxlitros',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='logistica',
            name='valorviaje',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reparaciones',
            name='fechasalida',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
