# Generated by Django 4.2.7 on 2024-02-14 13:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0014_reparaciones_apto_traslado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tanque',
            fields=[
                ('nombre', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('capacidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_combustible', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Repostaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tanque', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.tanque')),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consumo_litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_consumo', models.DateTimeField()),
                ('hskmactuales', models.IntegerField()),
                ('precinto_entrada', models.IntegerField()),
                ('precinto_salida', models.IntegerField()),
                ('observaciones', models.CharField(max_length=600)),
                ('chofer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.choferes')),
                ('interno', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos')),
                ('tanque', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.tanque')),
            ],
        ),
    ]
