# Generated by Django 4.2.7 on 2024-02-20 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0001_initial_squashed_0015_consumo_repostaje_tanque_delete_consumos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alquilerequipos',
            options={'permissions': [('puede_ver_alquilados', 'Puede ver los alquilados')]},
        ),
        migrations.AlterModelOptions(
            name='consumo',
            options={'permissions': [('puede_ver_consumo', 'Puede ver los consumos')]},
        ),
        migrations.AlterModelOptions(
            name='disponibilidadequipos',
            options={'permissions': [('puede_ver_disponibilidad', 'Puede ver la disponibilidad')]},
        ),
        migrations.AlterModelOptions(
            name='historialservice',
            options={'permissions': [('puede_ver_historial_service', 'Puede ver los services')]},
        ),
        migrations.AlterModelOptions(
            name='internos',
            options={'permissions': [('puede_ver_internos', 'Puede ver los internos')]},
        ),
        migrations.AlterModelOptions(
            name='logistica',
            options={'permissions': [('puede_ver_logistica', 'Puede ver la logistica')]},
        ),
        migrations.AlterModelOptions(
            name='novedades',
            options={'permissions': [('puede_ver_novedades', 'Puede ver la novedades')]},
        ),
        migrations.AlterModelOptions(
            name='reparaciones',
            options={'permissions': [('puede_ver_reparaciones', 'Puede ver las reparaciones')]},
        ),
        migrations.AlterModelOptions(
            name='repostaje',
            options={'permissions': [('puede_ver_repostaje', 'Puede ver los repostajes')]},
        ),
        migrations.AlterModelOptions(
            name='requerimientotraslado',
            options={'permissions': [('puede_ver_requerimientos', 'Puede ver los requerimientos')]},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'permissions': [('puede_ver_services', 'Puede ver los services')]},
        ),
        migrations.AlterModelOptions(
            name='tanque',
            options={'permissions': [('puede_ver_tanques', 'Puede ver los tanques')]},
        ),
    ]
