# Generated by Django 4.2.7 on 2024-02-27 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0016_alter_alquilerequipos_options_alter_consumo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TanqueAceite',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tipo_aceite', models.CharField(max_length=100)),
                ('capacidad_aceite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_aceite', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'permissions': [('puede_ver_aceites', 'Puede ver los aceites')],
            },
        ),
        migrations.CreateModel(
            name='RepostajeAceite',
            fields=[
                ('remito', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_repostaje', models.DateTimeField()),
                ('cantidad_repostada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.CharField(max_length=500)),
                ('reservorio_aceite', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.tanqueaceite')),
            ],
            options={
                'permissions': [('puede_ver_cargarrepostaje', 'Puede ver los repostajes de aceites')],
            },
        ),
        migrations.CreateModel(
            name='ConsumoAceite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_consumida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_consumo', models.DateTimeField()),
                ('hskmactuales', models.IntegerField()),
                ('observaciones', models.CharField(max_length=500)),
                ('chofer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.choferes')),
                ('interno', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.internos')),
                ('tanque_aceite', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tablamadre.tanqueaceite')),
            ],
            options={
                'permissions': [('puede_ver_consumoaceite', 'Puede ver los consumos de aceite')],
            },
        ),
    ]
