# Generated by Django 4.2.7 on 2024-03-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablamadre', '0017_tanqueaceite_repostajeaceite_consumoaceite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reparaciones',
            name='interno',
        ),
        migrations.RemoveField(
            model_name='reparaciones',
            name='mecanico_encargado',
        ),
        migrations.RemoveField(
            model_name='reparaciones',
            name='taller',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='internos',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='logistica',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='partesdiarions',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='reparaciones',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='services',
        ),
        migrations.RemoveField(
            model_name='tablamadre',
            name='unidadesdeproduccion',
        ),
        migrations.DeleteModel(
            name='PartesDiarios',
        ),
        migrations.DeleteModel(
            name='Reparaciones',
        ),
        migrations.DeleteModel(
            name='TablaMadre',
        ),
    ]
