# Generated by Django 4.2.7 on 2024-03-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NovedadTemporal',
            fields=[
                ('interno', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('marca', models.CharField(default='Generica', max_length=256)),
                ('modelo', models.CharField(default='Generico', max_length=512)),
                ('reparado', models.CharField(max_length=512)),
                ('tipo_falla', models.CharField(default='Generica', max_length=512)),
                ('fecha', models.CharField(default='Generica', max_length=512)),
                ('informacion', models.CharField(default='No hay informacion', max_length=512)),
                ('ingreso_hs_km', models.IntegerField(default=1)),
                ('chofer', models.CharField(default='No tiene chofer', max_length=512)),
            ],
        ),
    ]
