# Generated by Django 4.2.7 on 2024-01-22 19:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NovedadTemporal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('interno', models.CharField(max_length=15)),
                ('reparado', models.CharField(max_length=512)),
                ('tipo_falla', models.CharField(default='Generica', max_length=512)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('informacion', models.CharField(default='No hay informacion', max_length=512)),
                ('ingreso_hs_km', models.IntegerField(default=1)),
                ('chofer', models.CharField(default='No tiene chofer', max_length=512)),
            ],
        ),
    ]
