# Generated by Django 4.2.7 on 2024-01-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedadtemporal',
            name='marca',
            field=models.CharField(default='Generica', max_length=256),
        ),
        migrations.AddField(
            model_name='novedadtemporal',
            name='modelo',
            field=models.CharField(default='Generico', max_length=512),
        ),
    ]
