# Generated by Django 4.2.7 on 2024-01-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0002_novedadtemporal_marca_novedadtemporal_modelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novedadtemporal',
            name='id',
        ),
        migrations.AlterField(
            model_name='novedadtemporal',
            name='interno',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
