# Generated by Django 4.2.7 on 2024-01-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0003_remove_novedadtemporal_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedadtemporal',
            name='fecha',
            field=models.CharField(default='Generica', max_length=512),
        ),
    ]
