# Generated by Django 4.2.7 on 2023-11-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parted',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=512)),
                ('unidad', models.CharField(max_length=512)),
                ('marca', models.CharField(max_length=512)),
                ('modelo', models.CharField(max_length=512)),
                ('dominio', models.CharField(max_length=512)),
                ('fechaservicio', models.DateField()),
                ('fechaparte', models.DateField()),
                ('ubicacion', models.CharField(max_length=512)),
                ('up', models.CharField(max_length=255)),
                ('unidades', models.CharField(max_length=255)),
                ('estado_equipo', models.CharField(max_length=255)),
                ('hsxkm', models.IntegerField()),
                ('planrealizadohs', models.CharField(max_length=512)),
                ('proximoserv', models.IntegerField()),
                ('hsXkmActuales', models.IntegerField()),
                ('hsXkilometros', models.IntegerField()),
                ('estadoServ', models.CharField(max_length=512)),
            ],
        ),
    ]
