# Generated by Django 4.2.7 on 2024-04-18 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cuit', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contacto', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'permissions': [('puede_ver_proveedores', 'Puede ver las proveedores'), ('puede_crear_proveedores', 'Puede crear las proveedores')],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionProveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('calidad', models.PositiveIntegerField()),
                ('cumplimiento_plazo_entrega', models.PositiveIntegerField()),
                ('precio_plazo', models.PositiveIntegerField()),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Evaluacion de Proveedor',
                'verbose_name_plural': 'Evaluaciones de Proveedores',
                'permissions': [('puede_ver_evaluaciones_proveedores', 'Puede ver las evaluaciones de proveedores'), ('puede_crear_evaluaciones_proveedores', 'Puede crear las evaluaciones de proveedores')],
            },
        ),
    ]
